apiVersion: v1
kind: Pod
metadata:
  name: labels
  Namespace: roboshop
  labels: 
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx